apiVersion: v1
kind: Service
metadata:
  name: chirpstack
  namespace: {{ .Release.Namespace }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.chirpstack.host }}
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: chirpstack
  type: ClusterIP
