apiVersion: v1
kind: Service
metadata:
  name: helium-sidecar
  namespace: helium
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8081"
spec:
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: helium-sidecar
  type: ClusterIP
