apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: chirpstack-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: external-secrets
    kind: ClusterSecretStore
  target:
    name: chirpstack-secrets
    creationPolicy: Owner
  data:
  - secretKey: POSTGRESQL_PASSWORD
    remoteRef:
      key: chirpstack/postgres-chirpstack-credentials # AWS Secrets Manager secret name
      property: password # AWS Secrets Manager secret key
  - secretKey: REDIS_PASSWORD
    remoteRef:
      key: chirpstack/redis-chirpstack-credentials
      property: password
  - secretKey: CHIRPSTACK_API_SECRET
    remoteRef:
      key: chirpstack/chirpstack-api-secret
      property: secret
