apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mqtt-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: external-secrets
    kind: ClusterSecretStore
  target:
    name: mqtt-secrets
    creationPolicy: Owner
  data:
  - secretKey: pwfile
    remoteRef:
      key: chirpstack/mqtt-pwfile #AWS Secrets Manager secret name
