projects:
  chirpstack:
    namespace: argocd
    description: Chirpstack
    sourceRepos:
    - '*'
    destinations:
    - name: '*'
      namespace: 'chirpstack'
      server: '*'
    clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  helium:
    namespace: argocd
    description: 'Helium Sidecar'
    sourceRepos:
    - '*'
    destinations:
    - name: '*'
      namespace: 'helium'
      server: '*'
    clusterResourceWhitelist:
    - group: '*'
      kind: '*'

applications:
  chirpstack:
    namespace: argocd
    project: chirpstack
    source:
      repoURL: <add_me_in_helm_release>
      targetRevision: HEAD
      path: chirpstack
      helm:
        valueFiles:
          - values.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: chirpstack
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
  helium:
    namespace: argocd
    project: helium
    source:
      repoURL: <add_me_in_helm_release>
      targetRevision: HEAD
      path: helium
      helm:
        valueFiles:
          - values.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: helium
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
      - CreateNamespace=true
