apiVersion: v1
kind: Service
metadata:
  name: chirpstack-gateway-bridge
  namespace: {{ .Release.Namespace }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-type: external
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.chirpstack-gateway-bridge.host }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.global.enabledRegions }}
    - name: {{ .labelName }}
      port: {{ .chirpstack-gateway-bridge.port }}
      targetPort: {{ .chirpstack-gateway-bridge.targetPort }}
      protocol: UDP
  {{- end }}
  selector:
    app: chirpstack-gateway-bridge
  type: LoadBalancer
  loadBalancerClass: service.k8s.aws/nlb
