apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mosquitto
  namespace: chirpstack
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/group.name: chirpstack
    # alb.ingress.kubernetes.io/healthcheck-path: /health
    # alb.ingress.kubernetes.io/healthcheck-port: "8081"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":1884}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-redirect: "1884"
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
  - host: {{ .Values.mosquitto.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mqtt-external
            port:
              number: 1884
