apiVersion: v1
kind: Service
metadata:
  name: mqtt-internal
  namespace: chirpstack
  labels:
    app: mosquitto
spec:
  ports:
    - port: 1883
      targetPort: 1883
      protocol: TCP
      name: mqtt-internal
  type: ClusterIP
  selector:
    app: mosquitto
---
apiVersion: v1
kind: Service
metadata:
  name: mqtt-external
  namespace: chirpstack
  labels:
    app: mosquitto
spec:
  ports:
    - port: 1884
      targetPort: 1884
      protocol: TCP
      name: mqtt-external
  type: ClusterIP
  selector:
    app: mosquitto
