apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mosquitto
  namespace: chirpstack
spec:
  selector:
    matchLabels:
      app: mosquitto
  serviceName: "mosquitto"
  replicas: 1
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: mosquitto
        image: {{ .Values.mosquitto.image.repository }}:{{ .Values.mosquitto.image.tag }}
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 1883
            name: mqtt-internal
          - containerPort: 1884
            name: mqtt-external
        livenessProbe:
          tcpSocket:
            port: 1883
          initialDelaySeconds: 5
          periodSeconds: 15
        readinessProbe:
          tcpSocket:
            port: 1883
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
          - name: config
            mountPath: /mosquitto/config
      volumes:
        - name: config
          configMap:
            name:  mosquitto
