global:

  # Should be the ARN of the AWS Certificate Manager certificate that was created for the Hosted Zone
  certArn: arn:aws:acm:us-east-1:014498639521:certificate/bdee2b15-2021-483d-bdbb-2db242753871

  # LoRaWAN regions enabled in Chirpstack
  # Each 'name' parameter must match the 'id' field from the corresponding ./chirpstack/files/region-*.toml file
  # The `labelName`, `file`, and `path` parameters should follow the format provided in the examples below.
  # The `gateway.port` and `gateway.targetPort` values will respectively become the UDP listening port on the
  # AWS Network Load Balancer in front of the Chirpstack Gateway Bridge instances and the UDP listening port on the
  # Chirpstack Gateway Bridge pod(s).
  enabledRegions:
    - name: us915_1
      labelName: us915-1
      file: region_us915_1.toml
      path: files/region_us915_1.toml
      gateway:
        port: 1700
        targetPort: 1700

chirpstack:

  # Hostname for the Chirpstack dashboard
  host: chirpstack.lns.test-helium.com

  # Hostname for the ElastiCache Redis Cluster
  redisHost: master.chirpstack-redis.8pxc3z.use1.cache.amazonaws.com:6379

  # Hostname for the RDS Postgres Instance
  postgresHost: chirpstack-rds.cl0seme6msyf.us-east-1.rds.amazonaws.com

  # Security Group ID for the chirpstack-alb security group
  alb:
    securityGroupId: sg-0ebc1661352eb44bf # chirpstack-alb

  # https://hub.docker.com/r/chirpstack/chirpstack/tags
  image:
    repository: chirpstack/chirpstack
    tag: 4.4

  config:

    # devAddr(s) purchased from Helium Foundation
    # https://docs.helium.com/iot/run-an-lns/buy-an-oui#purchasing-oui-and-devaddr-slab
    devAddrPrefixes:
      - prefix: 780001B0/29

    # This is the Helium Net ID. It should not be changed.
    netId: 00003C

gateway:

  # Hostname for the Chirpstack Gateway Bridge instance(s)
  host: gwb.lns.test-helium.com

  # https://hub.docker.com/r/chirpstack/chirpstack-gateway-bridge/tags
  image:
    repository: chirpstack/chirpstack-gateway-bridge
    tag: 4.0

mosquitto:

  # Hostname for the MQTT server
  host: mqtt.lns.test-helium.com

  # https://hub.docker.com/_/eclipse-mosquitto/tags
  image:
    repository: eclipse-mosquitto
    tag: 2.0

  # Security Group ID for the mqtt-alb security group
  nlb:
    securityGroupId: sg-031cdf055d392b90c # mqtt-nlb
