global:
  cert: arn:aws:acm:us-east-1:533916786372:certificate/cd721467-8562-4ecf-8cfa-c031df72ff50
  enabledRegions:
    - name: us915_1
      labelName: us915-1
      file: region_us915_1.toml
      path: files/region_us915_1.toml
      gateway:
        port: 1700
        targetPort: 1700
    - name: eu868
      labelName: eu868
      file: region_eu868.toml
      path: files/region_eu868.toml
      gateway:
        port: 1701
        targetPort: 1700

chirpstack:
  replicas: 1
  host: dashboard.chirpstack.test-helium.com
  alb:
    securityGroupId: sg-06b0809a1bd644098 # chirpstack-alb
  image:
    repository: chirpstack/chirpstack
    tag: 4.4
  config:
    devAddrPrefixes:
      - prefix: 780000F0/29
    netId: 00003C

gateway:
  host: gwb.chirpstack.test-helium.com
  image:
    repository: chirpstack/chirpstack-gateway-bridge
    tag: 4.0

mosquitto:
  host: mqtt.chirpstack.test-helium.com
  image:
    repository: eclipse-mosquitto
    tag: 2.0
  nlb:
    securityGroupId: sg-09e5d12122d36c052 # mqtt-nlb
