apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: helium-keypair
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: external-secrets
    kind: ClusterSecretStore
  target:
    name: helium-keypair
    creationPolicy: Owner
  data:
  - secretKey: keypair.bin
    remoteRef:
      key: chirpstack/helium-keypair #AWS Secrets Manager secret name
      decodingStrategy: Base64
