apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: helium-settings
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: external-secrets
    kind: ClusterSecretStore
  target:
    name: helium-settings
    creationPolicy: Owner
  data:
  - secretKey: settings.toml
    remoteRef:
      key: chirpstack/helium-settings # AWS Secrets Manager secret name
